# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20160808_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='assigned_at',
            field=models.DateTimeField(),
        ),
    ]
